import { Inter } from "next/font/google";

// import './globals.css'
import "./style.css";
import "bootstrap/dist/css/bootstrap.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg_image">
        <nav class="navbar navbar-expand-lg fixed-top bg-primary">
          <div class="container-fluid">
            <a class="navbar-brand">
              <img
                src="https://shivshankar9.github.io/Student-portal/images/logo.png"
                alt=""
                width="50"
                height="50"
                class="d-inline-block"
              />
              <b className="text-white">Student portal</b>
            </a>
            <button class="navbar-toggler" type="button" id="navbarToggle">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div
              class="collapse navbar-collapse nav justify-content-end"
              id="navbarNav"
            >
              <ul class="navbar-nav ml-auto" id="ul">
                <li class="nav-item">
                  <Link href="/login" class="nav-link active text-white">
                    Login
                  </Link>{" "}
                </li>
                <li class="nav-item">
                  <Link href="/registration" class="nav-link active text-white">
                    Registration
                  </Link>{" "}
                </li>
                <li class="nav-item">
                  <Link href="/contact" class="nav-link active text-white">
                    Contact
                  </Link>{" "}
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        <br></br>
        {/*------------ end navbar area -------------*/}
        {children}
      </body>
    </html>
  );
}
